version: '3.9'
name: dock-php-apache-1
services:
  php_apache:
    container_name: kmd_l5dc_php
    image: nimmis/apache-php7
    volumes:
      - ./app/public:/var/www/html:Z
    ports:
      - 8085:80
    restart: always
